#Persisted Channels storage file  by EFI Analytics, Inc
#Last Saved on: Mon Jul 13 22:09:32 EEST 2026
#Mon Jul 13 22:09:32 EEST 2026
_(\ (\ deltatime\ <\ 1000.0\ )\ )\ ?\ ((\ (\ tsFuelFlowGph\ *\ deltatime\ /\ 3600.0\ )\ ))\ \:\ (0.0)=0.002128168664654579
_(\ (\ tsInputSpeedMPH\ *\ 1.60934\ )\ /\ 3600.0\ *\ deltatime\ )=0.0
_(\ tsInputSpeedMPH\ /\ 3600.0\ *\ deltatime\ )=0.0
