#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Fri Jul 03 20:25:43 EEST 2026
converterStall=
injectorSize=731
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1839
