#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Mon Jul 13 22:00:26 EEST 2026
converterStall=
injectorSize=710
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1839
